# Generated by Django 2.2.1 on 2019-05-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='process_id',
            field=models.IntegerField(null=True),
        ),
    ]
