# Generated by Django 2.2.1 on 2019-05-21 13:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shortener', '0004_urlconfirmation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UrlConfirmation',
            new_name='UrlManagement',
        ),
    ]
